# Generated by Django 3.2.7 on 2023-06-26 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('city', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
